workers_dev = true
name = "reactrouter-cloudflare"
compatibility_date = "2024-11-18"
main = "./build/server/index.js"
assets = { directory = "./build/client/" }


[vars]
VALUE_FROM_CLOUDFLARE_ENV = 'VALUE_FROM_CLOUDFLARE_ENV'

[env.production.vars]
VALUE_FROM_CLOUDFLARE_ENV = 'VALUE_FROM_CLOUDFLARE_PROD_ENV'
